#!/bin/bash
basedir=/anope
confdir=$basedir/conf
env=$(compgen -v |sed 's/^/$/' | paste -s -d ':')

mkdir -p $confdir

for template in $(find $basedir/templates -type f); do
  output=$confdir/$(basename $template)
  echo "Writing $output"
  envsubst $env < $template > $output
done

/anope/bin/geoipupdate.sh 

exec /anope/bin/services -debug -nofork --config=services.conf --confdir=$confdir

